# Generated by Django 5.2.5 on 2025-10-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='plaid_link_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='plaid_public_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
