# Generated by Django 5.2.5 on 2025-11-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_loanapplication_plaid_link_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
